---
title: "week_04"
format: html
---

9/18/26
When have a table with two rows GEOID and med_inc.23, to join them must have the same left rows and then you do
left_join(income_23,incoe_is, by= “GEOID”
Anything that dosent have a match gets dropped out and input a NA
If you want everything that's in both tables you need to do full+join
Inner join= joins rows 

Spatial section:
get-acs(..., geometry equals TRUE)
When input this you get a new column called geometry and says things like POLYGON( 1-75.45, 39.95))
Geometry column is called “sticky” → it follows you around, but often need to hide it because it slows down other operations & it comes back at the end
In GIS data in .Shp or -gdb,  R data features are Sf (simple features)
Coordinate reference systems (CRS) [2 main types]
Geographic= live on a sphere, units: degrees, line ofs of lat and long on NAD83 line up differently than GRS 80 & WGS84 (standard for GPS)
The datums important because the coordinate systems are different so can end up in a different point
If measurements are about 200 meters off then your normally in different datums when trying to lighn up data
Projected= often distorted in one or two of these ways: shape (good shape→ conrofmal conic), areas (good → equal area), distance (good → equal distance), direction (good → mercator); goof for local mapping; measured in ft or meters
Line of tangency= line where theres no distortion as you get further awy form the line get more distorted
Many projections distort certain areas because no projection can be perfect
St_crs(data) → will tell you all the details – do this first because it will tell us the units
St-set-(rs() → Use for adding the correct label
St_transform ( data, new coordinate system ex. 2272→ change the coordinate system
St_buffer (stations, 500) → in this example sayig I need to make a buffer around the stations that are within 500 units of the layer, if you want to change the units then you have to do the math yourself

Functions for spatial analysis:

Anything that is spatial begins with St
St_intersects → 
St_touches → 
St_within → 
St_filter() → count the tracts
Ex. how many tracts near ½ mile from the station?
St_intersection () → shapes change → creates more shapes ushually
Shapes actually change and you  create new polygons every time they  intersect
St_union () → get everything
St_join(stations, tracts) → maybe we want to join the stations and tracts, all the stations will stay there but will assign the tract value to the station
St_distance → returns a matrix with the distance between all of the stations and the tracts
